import type { Metadata } from "next";
import {Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Header from "./componenets/Header";
import Marque from "./componenets/Marque";
import Headerpage from "./componenets/Header";
import { Suspense } from "react";
import Footer from "./componenets/Footer";



const notoserifbangla = Noto_Serif_Bengali({
  variable: "--font-geist-sans",
  subsets: ["latin","bengali"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html 
      lang="en"
      data-theme="light"
      className={`${notoserifbangla.className} h-full antialiased scroll-smooth`}
    >
      <body className="min-h-full flex flex-col bg-slate-100">
<Suspense fallback={<p>Loading...</p>}>
<Header></Header>
</Suspense>
<Marque></Marque>

        {children}
        <Footer></Footer>
        </body>
    </html>
  );
}
